### ISSUE TITLE
Fix dependecies

### ISSUE THREAD

**Issue by yordis** [KamilLelonek/exnumerator#3]
I am getting this because your package have `ex_doc` in `prod` as you can see and my dependency is only for `dev`

```
* ex_doc (Hex package)
  the :only option for dependency ex_doc

  > In mix.exs:
    {:ex_doc, ">= 0.0.0", [env: :prod, repo: "hexpm", hex: "ex_doc", only: :dev, runtime: false, manager: :mix]}

  does not match the :only option calculated for

  > In deps/exnumerator/mix.exs:
    {:ex_doc, ">= 0.0.0", [env: :prod, hex: "ex_doc", repo: "hexpm", optional: false]}

  Remove the :only restriction from your dep
** (Mix) Can't continue due to errors on dependencies
```

I understand what you are doing with `mix.exs` and `deps` but it is failing so

**Comment by KamilLelonek** [comment]
Why do you use `exnumerator` only in development?

**Comment by yordis** [comment]
No, `ex_doc` is only for `dev` , read the output

I have `{:exnumerator, "~> 1.2"},` for my `exnumerator` dependency

**Comment by yordis** [comment]
Fixed!
