### ISSUE TITLE
How about map values with string instead of atom?

### ISSUE THREAD

**Issue by jung-hunsoo** [KamilLelonek/exnumerator#4]
I'm trying exnumerator now, and found that only atom type is allowed for the values which string doesn't.

Since it won't harm the functionality, it'd be better using with string not to consume erlang's atom limitation.

While the developers feel comfortable with atom logically, which the name itself represent their values are atomic, the DB will likely have its values with string physically. And even we no more need to use `:erlang.atom_to_binary/2`, right?

**Comment by KamilLelonek** [comment]
I'd like the suggestion. Can you prepare Pull Request with the changes?

**Comment by jung-hunsoo** [comment]
OK, give me some minutes. :-)

**Comment by mbenatti** [comment]
I not agree with you guys, we need to keep both String and Atoms,
If you change only to String change the version to 2.0 because this is break all other applications using atoms.

I spend some minutes figuring out why the atom do not work anymore, its not correct to take it off...

**Comment by KamilLelonek** [comment]
@mbenatti 

1. Everything is documented
2. Semantic versioning indicates breaking change

So if you

> spend some minutes figuring out why the atom do not work anymore

then you probably didn't care about versioning and didn't read the docs. Am I correct?

**Comment by mbenatti** [comment]
@KamilLelonek It is the opposite, I care, because of this I send a message here, I use exnumerator in some projects and this change will break the code, and its not correct acording semver.org(semantic).

Can I send a pull request to support both atom and String?

**Comment by KamilLelonek** [comment]
Yes, please open a PR for that.

**Comment by jung-hunsoo** [comment]
It seems a useful PR, since more flexible and usable are going to be achieved. Now guys may choose their syntax with compatibility preserved.
